name = "e-blog"
main = "src/index.ts"
compatibility_date = "2025-05-01"

[vars]
SITE_TITLE = "E-Blog"
SITE_DESCRIPTION = "A personal blog on Cloudflare"

# ADMIN_PASSWORD should be set via: wrangler secret put ADMIN_PASSWORD

[[d1_databases]]
binding = "DB"
database_name = "e-blog-db"
database_id = "47d3c96d-49af-4362-b797-03d91e161bc9"

[[kv_namespaces]]
binding = "KV"
id = "6c1ac56c916443749ba9a43ed50613b1"
